### ISSUE TITLE
Playlist settings window on YouTube blocked.

### ISSUE THREAD

**Issue by mimmiechan** [betterwebleon/international-list#2]
It blocks the Playlist settings window on YouTube.
To reproduce: Log in/create a YouTube/Google account. Create a playlist (cannot be another user's playlist) by going to a video click "Add to" and choose a playlist or choose to "Create a new playlist". Click the hamburger menu in the upper left corner of the website, click on the Playlist's name. Click on "Playlist settings".

I am using uBlock Origin on Firefox 70 64-bit on Windows 10.

**Comment by betterwebleon** [comment]
Thank you for report. It should be fixed now.
